import Constants from "@/utils/constants";
import Head from "next/head";


const Header = () => {
    return (
      <>
      <Head>
        <title>{Constants.appTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      </>
    );
  }

export default Header;